name: tests-payments

on:
<<<<<<< HEAD
  pull_request
=======
  pull_request:
    paths: 
      - 'payments/**'
>>>>>>> master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
